# spec/acceptance/nodesets/default.yml
#HOSTS:
#  ubuntu-14-04:
#    platform: ubuntu-14.04-x64
#    hypervisor: vagrant
#    box: ubuntu-14.04-amd64-phusionpassenger
#    #box_url: 
#    #pe_ver: 
#    #ip: 
#    #roles: 
HOSTS:
  ubuntu-server-1404-x64:
    roles:
      - master
    platform: ubuntu-12.04-amd64
    box: puppetlabs/ubuntu-14.04-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm
    hypervisor: vagrant
CONFIG:
  type: foss
